name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: perfectSymphony/notes@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: perfectSymphony/perfectSymphony.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: notes/docs/.vuepress/dist/
